### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by ServerProcessor** [FunctionAnalysis/QuantumExperience#1]
![ppp](https://cloud.githubusercontent.com/assets/24603292/21472071/89673f24-caee-11e6-91bd-74650662a3bc.png)
![ppp1](https://cloud.githubusercontent.com/assets/24603292/21472072/8ec007d0-caee-11e6-88b4-be6d4fdcb215.png)

**Comment by FunctionAnalysis** [comment]
After reviewing the pull request, I don't find this to be an issue with the repository.  Having requested modifications to the suggested merge, I think adding images without textual context does not add value, nor solve any issues with this repository.
